dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: mse-c4e5aec3-p.zk.mse.aliyuncs.com:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000
    filter: dubboLogFilter

server:
  port: 8062
logging:
  level:
    root: info