dubbo:
  application:
    name: dubbo-provider
  registry:
    address: mse-c4e5aec3-p.zk.mse.aliyuncs.com:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000

server:
  port: 8061